sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t fimperioli/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fimperioli/react-test npm test -- --coverage

after_success:
  - docker build -t fimperioli/multi-docker-client ./client
  - docker build -t fimperioli/multi-docker-server ./server
  - docker build -t fimperioli/multi-docker-worker ./worker
  - docker build -t fimperioli/multi-docker-nginx ./nginx
  #login to docker cli using env variables and only a single command
  - echo "5M92tGRHrjq&" | docker login -u "fimperioli" --password-stdin
  #push to docker hub using docker cli login
  - docker push fimperioli/multi-docker-client
  - docker push fimperioli/multi-docker-server
  - docker push fimperioli/multi-docker-worker
  - docker push fimperioli/multi-docker-nginx
deploy:
  provider: elasticbeanstalk
  region: eu-south-1
  app:  docker-multi
  env:  Dockermulti-env
  bucket_name:  elasticbeanstalk-eu-south-1-734043432216
  bucket_path:  docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY